# 제품모드 
[build]
  command = "pnpm build" # 빌드 명령
  functions = "functions" # Netflify 서버리스 함수가 작성된 디렉토리 지정
  publish = "dist" # 프로젝트 빌드 결과의 디렉토리 지정 

# 개발모드 
[dev]
  framework = "#custom" # Netlify가 감지할 프로젝트 유형 지정
  command = "pnpm dev" # 연결할 프로젝트의 개발서버를 실행하는 명령(script) 지정
  targetPort = 4321 # 연결할 프로젝트의 개발서버의 포트번호 지정 
  port = 8888 # 출력할 Netlify 서버의 포트번호를 지정 
  publish = "dist" # 프로젝트의 정적 콘텐츠 디렉토리를 지정
  autoLaunch = false # Netlify 서버가 준비되면 자동으로 브라우저를 오픈할 것인지 지정

[functions]
  directory = "src/shared/functions"
  